// import 'dart:convert';
// import 'package:get/get.dart';
// import 'package:http/http.dart' as http;
// import 'package:smart_absen/app/data/kehadiran_response.dart'; 


// class KehadiranController extends GetxController {
//   var isLoading = false.obs;
//   var kehadiranList = <Data>[].obs;

//   @override
//   void onInit() {
//     super.onInit();
//     fetchKehadiran();
//   }

//   Future<void> fetchKehadiran() async {
//     try {
//       isLoading(true);
//       final response = await http.get(Uri.parse('https://192.168.144.189/api/kehadiran'));

//       if (response.statusCode == 200) {
//         final jsonResponse = json.decode(response.body);
//         Autogenerated kehadiranData = Autogenerated.fromJson(jsonResponse);
//         kehadiranList.value = kehadiranData.data ?? [];
//       } else {
//         Get.snackbar("Error", "Gagal memuat data");
//       }
//     } catch (e) {
//       Get.snackbar("Error", e.toString());
//     } finally {
//       isLoading(false);
//     }
//   }
// }
